Fix typo in autopkgtests configuration-tracing affecting armhf and armel
Normalization of the value didn't work as for some reason 'OS' was spelled
with capital letters so the normalization didn't find and normalize the
correct value, leading to autopkgtests on armhf and armel to fail on:

  Tracing: /usr/sbin/mariadbd --verbose --help
  diff --ignore-space-change -u mariadbd-verbose-help.expected mariadbd-verbose-help.actual
  --- mariadbd-verbose-help.expected	2023-03-26 01:26:42.000000000 -0500
  +++ mariadbd-verbose-help.actual	2023-03-26 13:16:55.820234953 -0500
  @@ -3029,7 +3029,7 @@
  -version-compile-os                                           debian-linux-gnu
  +version-compile-os                                           debian-linux-gnueabi
  Error: Output from '/usr/sbin/mariadbd --verbose --help' did NOT match what was expected